# _config.yml

# Site settings
title: "Abhigyan Majumdar"
description: "Dynamic Modeling | Optimal Control | Supervisory Controls | Hardware-in-the-Loop"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abhigyan9.github.io" # Replace with your GitHub Pages URL

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Author settings
author:
  name: "Abhigyan Majumdar"
  email: "abmajumdar@ucdavis.edu"

# Social links (update with your actual usernames if available)
#twitter_username: "your_twitter_username"
github_username: "abhigyan9"
linkedin_username: "abhigyanmajumdar"

# Build settings
markdown: kramdown
